{% extends "layout_default.phtml" %}
{% set active_menu = 'craftsrv' %}
{% block meta_title %}{% trans 'CraftSRV' %}{% endblock %}

{% block top_content %}
<div class="stats">
    <ul>
        <li class="last"><a href="{{ 'craftsrv'|alink }}" class="count grey" title="">0</a><span>{% trans 'Total' %}</span></li>
    </ul>
    <div class="fix"></div>
</div>
{% endblock %}

{% block content %}
<div class="widget simpleTabs">

    <ul class="tabs">
        <li><a href="#tab-index">{% trans 'CraftSRV' %}</a></li>
        <li><a href="#tab-new">{% trans 'New CraftSRV' %}</a></li>
    </ul>
    <div class="tabs_container">
        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-index">
            {{ mf.table_search }}
            <table class="tableStatic wide">
                <thead>
                    <tr>
                        <td style="width: 2%"><input type="checkbox" class="batch-delete-master-checkbox"/></td>
                        <td>{% trans 'Name' %}</td>
                        <td>{% trans 'Host' %}</td>
                        <td>{% trans 'Api version' %}</td>
                        <td width="13%">&nbsp;</td>
                    </tr>
                </thead>

                <tbody>
                    {% set craftsrvMachines = admin.craftsrv_get_list({"per_page":30, "page":request.page}|merge(request)) %}
                    {% for craftsrv in craftsrvMachines.list %}
                    <tr>
                        <td><input type="checkbox" class="batch-delete-checkbox" data-item-id="{{ craftsrv.id }}"/></td>
                        <td><a href="{{ 'craftsrv/manage'|alink }}/{{ craftsrv.id }}" title="{{ craftsrv.name }} {{ craftsrv.last_name }}">{{ craftsrv.name}}</a></td>
                        <td><a href="{{ 'craftsrv/manage'|alink }}/{{ craftsrv.id }}" title="{{ craftsrv.host }} {{ craftsrv.last_name }}">{{ craftsrv.host}}</a></td>
                        <td><a href="{{ 'craftsrv/manage'|alink }}/{{ craftsrv.id }}" title="{{ craftsrv.version }}">{{ craftsrv.version }}</a></td>
                        <td class="actions">
                            <a class="bb-button btn14" href="{{craftsrv.host}}" target="_blank"><img src="images/icons/dark/cog.png" alt=""></a>
                            <a class="bb-button btn14 api-link" data-api-msg="Connected" href="{{ 'api/admin/craftsrv/craftsrv_test_connection'|link({'id' : craftsrv.id}) }}" title="Test connection"><img src="images/icons/dark/signal.png" alt=""></a>
                            <a class="bb-button btn14" href="{{ '/craftsrv/manage'|alink }}/{{craftsrv.id}}"><img src="images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?" data-api-redirect="{{ 'craftsrv'|alink }}" href="{{ 'api/admin/craftsrv/delete'|link({'id' : craftsrv.id}) }}"><img src="images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="7">{% trans 'The list is empty' %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "partial_batch_delete.phtml" with {'action' : 'admin/craftsrv/batch_delete'} %}
            {% include "partial_pagination.phtml" with {'list': craftsrvMachines, 'url':'craftsrv'} %}
    	</div>

        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-new">
            <form method="post" action="{{ 'api/admin/craftsrv/create'|link }}" class="mainForm api-form save" data-api-redirect="{{ 'craftsrv'|alink }}">
                <div class="help">
                    <h3>{% trans 'CraftSRV' %}</h3>
                </div>
                <fieldset>
                    <div class="rowElem noborder">
                        <label>{% trans 'Name' %}:</label>
                        <div class="formRight">
                            <input type="text" name="name" value="{{request.name}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Host' %}:</label>
                        <div class="formRight">
                            <input type="text" name="host" value="{{request.host}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Version' %}:</label>
                        <div class="formRight">
                            <input type="text" name="version" value="{{request.version}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Token' %}:</label>
                        <div class="formRight">
                            <textarea name="token" cols="5" rows="4" required="required">{{request.token}}</textarea>
                        </div>
                        <div class="fix"></div>
                    </div>
                </fieldset>
                <fieldset>
                    <div class="help">
                        <h3>{% trans 'Ports' %}</h3>
                    </div>
                    <div class="rowElem noborder">
                        <label>{% trans 'Port range' %}:</label>
                        <div class="formRight moreFields">
                            <ul>
                                <li style="width: 50px"><input type="text" name="port_ranges_min" value="{{request.port_ranges_min|default(1)}}"/></li>
                                <li class="sep">-</li>
                                <li style="width: 50px"><input type="text" name="port_ranges_max" value="{{request.port_ranges_max|default(65535)}}" /></li>
                            </ul>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Restricted ports' %}:</label>
                        <div class="formRight">
                            <input type="text" name="restricted_ports" value="{{request.restricted_ports|default(0)}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <input type="submit" value="{% trans 'Create' %}" class="greyishBtn submitForm" />
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}