{% extends "layout_default.phtml" %}
{% set active_menu = 'craftsrv' %}
{% block meta_title %}{{ craftsrv.name }}{% endblock %}

{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'craftsrv'|alink }}">{% trans 'CraftSRV' %}</a></li>
    <li class="lastB">{{ craftsrv.name }}</li>
</ul>
{% endblock %}

{% block content %}

<div class="widget simpleTabs">

    <ul class="tabs">
        <li><a href="#tab-info">{% trans 'CraftSRV' %}</a></li>
        <li><a href="#tab-edit">{% trans 'Edit' %}</a></li>
    </ul>

    <div class="tabs_container">
        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-info">

            <div style="position: relative;">
                <img src="{{ craftsrv.logo_url }}" alt="" style="width : 200px ; right: 0; margin: 15px 15px 0 15px; position: absolute; border: 2px solid white; box-shadow: 0px 0px 10px 0px;"/>
            </div>
            
            <table class="tableStatic wide">
                <tbody>
                    <tr class="noborder">
                        <td style="width: 15%">ID:</td>
                        <td>{{ craftsrv.id }}</td>
                    </tr>

                    <tr>
                        <td>Name:</td>
                        <td><strong>{{ craftsrv.name }}</strong></td>
                    </tr>

                    <tr>
                        <td>Host:</td>
                        <td><strong>{{ craftsrv.host }}</strong></td>
                    </tr>

                    <tr>
                        <td>API Host:</td>
                        <td><strong class="{% if craftsrv.ip is defined %}green{% else %}red{% endif %}">{{ craftsrv.api_host }}</strong></td>
                    </tr>

                    <tr>
                        <td>API Token:</td>
                        <td  class="{% if craftsrv.ip is defined %}green{% else %}red{% endif %}">{{ craftsrv.token|truncate(30) }}</td>
                    </tr>

                    <tr>
                        <td>IP:</td>
                        <td>{{ craftsrv.ip|default('000.000.000.000') }}</td>
                    </tr>

                    <tr>
                        <td>Port range(s):</td>
                        <td>{{ craftsrv.port_ranges|default('All unused port') }}</td>
                    </tr>

                    <tr>
                        <td>Port(s) used:</td>
                        <td>{{ craftsrv.occupied_ports|default('-')|truncate(30) }}</td>
                    </tr>

                    <tr>
                        <td>Restricted ports:</td>
                        <td>{{ craftsrv.restricted_ports|default('-') }}</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <a href="{{ craftsrv.host }}" class="btnIconLeft mr10 mt5" target="_blank"><img src="images/icons/dark/adminUser.png" alt="" class="icon"><span>Login to CraftSRV panel</span></a>
                            <a href="{{ 'api/admin/craftsrv/delete'|link({'id' : craftsrv.id}) }}" data-api-confirm="Are you sure?" data-api-redirect="{{ 'craftsrv'|alink }}" class="btnIconLeft mr10 mt5 api-link" ><img src="images/icons/dark/trash.png" alt="" class="icon"><span>Delete</span></a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="tab_content nopadding" id="tab-edit">

            <div class="help">
                <h3>{% trans 'CraftSRV' %}</h3>
            </div>

            <form method="post" action="{{ 'api/admin/craftsrv/update'|link }}" class="mainForm api-form save" data-api-msg="{% trans 'CraftSRV updated' %}" data-api-redirect="{{ 'craftsrv/manage'|alink }}/{{ craftsrv.id }}" >
                <fieldset>
                    <div class="rowElem">
                        <label>{% trans 'Name' %}:</label>
                        <div class="formRight">
                            <input type="text" name="name" value="{{craftsrv.name}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Host' %}:</label>
                        <div class="formRight">
                            <input type="text" name="host" value="{{craftsrv.host}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Version' %}:</label>
                        <div class="formRight">
                            <input type="text" name="version" value="{{craftsrv.version}}" required="required"/>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Token' %}:</label>
                        <div class="formRight">
                            <textarea name="token" cols="5" rows="4" required="required">{{craftsrv.token}}</textarea>
                        </div>
                        <div class="fix"></div>
                    </div>
                    <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
                </fieldset>
            
            <div class="help">
                <h3>{% trans 'Ports' %}</h3>
            </div>
                <fieldset>

                    <div class="rowElem noborder">
                        <label>{% trans 'Port range(s)' %}</label>
                        {% set port_ranges = craftsrv.port_ranges|split('-') %}
                        <div class="formRight moreFields">
                            <ul>
                                <li style="width: 50px"><input type="text" name="port_ranges_min" value="{{ port_ranges.0 }}"/></li>
                                <li class="sep">-</li>
                                <li style="width: 50px"><input type="text" name="port_ranges_max" value="{{ port_ranges.1 }}" /></li>
                            </ul>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem noborder">
                        <label>{% trans 'Port(s) used' %}</label>
                        <div class="formRight">
                            <span>{{ craftsrv.occupied_ports }}</span>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem noborder">
                        <label>{% trans 'Restricted ports' %}</label>
                        <div class="formRight">
                            <input type="text" name="restricted_ports" value="{{ craftsrv.restricted_ports }}" />
                        </div>
                        <div class="fix"></div>
                    </div>

                    <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
                    <input type="hidden" name="id" value="{{ craftsrv.id }}"/>
                </fieldset>
            </form>
        </div>
    </div>
</div>

{% endblock %}